apiVersion: v1
kind: Service
metadata:
  name: zkserver
  labels:
    app: zkserver
spec:
  ports:
  - port: 2181
    name: client-port
  - port: 2888
    name: server-port
  - port: 3888
    name: leader-port
  clusterIP: None
  selector:
    app: zkserver
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zkserver
spec:
  selector:
    matchLabels:
      app: zkserver # has to match .spec.template.metadata.labels
  serviceName: "zkserver"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: zkserver # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: zkserver
        image: zookeeper/hdf3.2:v0.1
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","echo 'Stopping container...';source /usr/hdf/current/zookeeper-server/conf/zookeeper-env.sh ; env ZOOCFGDIR=/etc/zookeeper/conf /usr/hdf/current/zookeeper-server/bin/zkServer.sh stop"]
        ports:
        - containerPort: 2181
          name: client-port
        - containerPort: 2888
          name: server-port
        - containerPort: 3888
          name: leader-port    
        volumeMounts:
        - name: zookeeper
          mountPath: /zookeeper
  volumeClaimTemplates:
  - metadata:
      name: zookeeper
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi